name: account
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.0.0  # เพิ่ม firebase_core ก่อน
  firebase_auth: ^4.0.0   # เพิ่ม firebase_auth
  cloud_firestore: ^4.0.0  # เพิ่ม cloud_firestore (หากใช้)

  shared_preferences: ^2.5.2
    
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  provider: ^6.1.2
  intl: ^0.20.2
  sembast: ^3.8.2
  path: ^1.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/cs.jpg
    - assets/images/cst.jpg
    - assets/images/eh.jpg
    - assets/images/ns.png
    - assets/images/pt.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
